/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 package pkg351.diegolucasromero.ejercicio11;

import java.awt.Component;
import javax.swing.JCheckBox;

/**
 *
 * @author android-0174654321
 */
public class chef extends javax.swing.JFrame {

    /**
     * Creates new form chef
     */
    public chef() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cocido = new javax.swing.JRadioButton();
        plentejas = new javax.swing.JRadioButton();
        pjudias = new javax.swing.JRadioButton();
        lentejas = new javax.swing.JCheckBox();
        garbanzos = new javax.swing.JCheckBox();
        judias = new javax.swing.JCheckBox();
        nuez = new javax.swing.JCheckBox();
        chorizo = new javax.swing.JCheckBox();
        morcilla = new javax.swing.JCheckBox();
        colorante = new javax.swing.JCheckBox();
        laurel = new javax.swing.JCheckBox();
        cebolla = new javax.swing.JCheckBox();
        zanahoria = new javax.swing.JCheckBox();
        pescado = new javax.swing.JCheckBox();
        pimenton = new javax.swing.JCheckBox();
        btnComprobar = new javax.swing.JButton();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(cocido);
        cocido.setText("Cocido");
        cocido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cocido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(plentejas);
        plentejas.setText("Lentejas");
        plentejas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(pjudias);
        pjudias.setText("Judías");
        pjudias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lentejas.setText("Lentejas");

        garbanzos.setText("Garbanzos");

        judias.setText("Judías");

        nuez.setText("Nuez Moscada");
        nuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuezActionPerformed(evt);
            }
        });

        chorizo.setText("Chorizo");

        morcilla.setText("Morcilla");

        colorante.setText("Colorante");

        laurel.setText("Laurel");

        cebolla.setText("Cebolla");

        zanahoria.setText("Zanahoria");

        pescado.setText("Pescado");

        pimenton.setText("Pimentón");

        btnComprobar.setText("Comprobar");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        txt.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(cocido)
                                .addGap(36, 36, 36)
                                .addComponent(plentejas)
                                .addGap(48, 48, 48)
                                .addComponent(pjudias))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lentejas)
                                            .addComponent(chorizo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(garbanzos)
                                            .addComponent(morcilla)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cebolla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(zanahoria)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pescado)
                                    .addComponent(colorante)
                                    .addComponent(judias))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pimenton)
                                    .addComponent(nuez)
                                    .addComponent(laurel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnComprobar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cocido)
                    .addComponent(plentejas)
                    .addComponent(pjudias))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lentejas)
                    .addComponent(garbanzos)
                    .addComponent(judias)
                    .addComponent(nuez))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chorizo)
                    .addComponent(morcilla)
                    .addComponent(colorante)
                    .addComponent(laurel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cebolla)
                    .addComponent(zanahoria)
                    .addComponent(pescado)
                    .addComponent(pimenton))
                .addGap(18, 18, 18)
                .addComponent(btnComprobar)
                .addGap(18, 18, 18)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cocidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocidoActionPerformed

    private void nuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuezActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        comprobar();
    }//GEN-LAST:event_btnComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void comprobar(){
        
        //Comprobacion de cuantos jcheckbox estan seleccionados
        
        int a=getContentPane().getComponentCount();
        int b=0;
         txt.setText("Prueba de Nuevo");
        for(int x=0;x<a;x++){
                if(getContentPane().getComponent(x) instanceof JCheckBox){
                    JCheckBox check= (JCheckBox) getContentPane().getComponent(x);                  
                  if(check.isSelected()){   
                       b++;
                   }
                }
            }
        
        if(cocido.isSelected() && b==4){
            if(chorizo.isSelected()){
                if(morcilla.isSelected())
                    if(garbanzos.isSelected()){
                        if(zanahoria.isSelected()){
                            txt.setText("Correcto");
                        }
                    }            
            }
                         
        }else if(plentejas.isSelected() && b==5){
            if(chorizo.isSelected()){
                if(cebolla.isSelected())
                    if(lentejas.isSelected()){
                        if(zanahoria.isSelected()){
                            if(pimenton.isSelected()){
                                txt.setText("Correcto");
                            }
                        }
                    }            
            }
            
        }else if(pjudias.isSelected() && b==6){
            if(chorizo.isSelected()){
                if(cebolla.isSelected())
                    if(judias.isSelected()){
                        if(laurel.isSelected()){
                            if(nuez.isSelected()){
                                if(colorante.isSelected()){
                                    txt.setText("Correcto");
                                }                                
                            }
                        }
                    }            
            }
            
        }else{
            txt.setText("Prueba de Nuevo");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cebolla;
    private javax.swing.JCheckBox chorizo;
    private javax.swing.JRadioButton cocido;
    private javax.swing.JCheckBox colorante;
    private javax.swing.JCheckBox garbanzos;
    private javax.swing.JCheckBox judias;
    private javax.swing.JCheckBox laurel;
    private javax.swing.JCheckBox lentejas;
    private javax.swing.JCheckBox morcilla;
    private javax.swing.JCheckBox nuez;
    private javax.swing.JCheckBox pescado;
    private javax.swing.JCheckBox pimenton;
    private javax.swing.JRadioButton pjudias;
    private javax.swing.JRadioButton plentejas;
    private javax.swing.JLabel txt;
    private javax.swing.JCheckBox zanahoria;
    // End of variables declaration//GEN-END:variables
}
