/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg351.diegolucasromero.ejercicio3;

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiarriba = new javax.swing.JLabel();
        etiabajo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        etiarriba.setBackground(new java.awt.Color(153, 153, 153));
        etiarriba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiarriba.setText("              Etiqueta");
        etiarriba.setOpaque(true);
        etiarriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiarribaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiarribaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiarribaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                etiarribaMouseReleased(evt);
            }
        });
        getContentPane().add(etiarriba);
        etiarriba.setBounds(39, 50, 120, 119);

        etiabajo.setBackground(new java.awt.Color(0, 0, 0));
        etiabajo.setForeground(new java.awt.Color(153, 153, 153));
        etiabajo.setText("jLabel2");
        etiabajo.setOpaque(true);
        getContentPane().add(etiabajo);
        etiabajo.setBounds(70, 60, 119, 119);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiarribaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiarribaMouseReleased
        // TODO add your handling code here:
        etiarriba.setBounds(39,50,120,119);
        etiarriba.setText("Pulsado");
        
        
        
        
    }//GEN-LAST:event_etiarribaMouseReleased

    private void etiarribaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiarribaMouseEntered
        // TODO add your handling code here:
        etiarriba.setText("Pulsame");
    }//GEN-LAST:event_etiarribaMouseEntered

    private void etiarribaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiarribaMouseExited
        // TODO add your handling code here:
        etiarriba.setText("Etiqueta");
        
    }//GEN-LAST:event_etiarribaMouseExited

    private void etiarribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiarribaMousePressed
        // TODO add your handling code here:
        etiarriba.setBounds(70,60,119,119);
        etiarriba.setText("Está pulsado");
        
        
    }//GEN-LAST:event_etiarribaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame j = new NewJFrame();
                j.setSize(300,300);
                j.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiabajo;
    private javax.swing.JLabel etiarriba;
    // End of variables declaration//GEN-END:variables
}
